[sncast.devnet]
account = "account-1"
accounts-file = "/home/sophiemabel69/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:6050"

[sncast.sepolia]
account = "runesdao_account"
url = "https://rpc.starknet.lava.build/rpc/v0_9"
